### ISSUE TITLE
Google Page Speed Test and Web.dev don't recognize the webp images

### ISSUE THREAD

**Issue by mark-netalico** [yireo/Yireo_Webp#1]
The google Page Speed Test and Web.dev don't recognize the webp images. So its uncertain whether they're giving websites SEO "credit" for faster images.

Example site: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.vanproducts.com%2F

**Comment by jissereitsma** [comment]
It is corect: External tests do not pick up on the WebP images created by this extension. The reason is simple: Either you create a solution where all images are replaced for all browsers (including the ones that do not support WebP, hence breaking images in non-WebP browsers), or you create a custom solution for supporting WebP-images in WebP-browsers and non-WebP-images in non-WebP-images. The last option is the reason why you use this extension. However, this custom solution is custom - it is not reckognized in any of the extensions.

However, because the images that are handled by this extension are not containing any path to the original image anymore (scan the HTML source for `<img>` tags to see what I mean here), it is unlikely that these external tests are complaining about the images picked up by this extension.

My bet is that the tools are actually complaining about all of the other images that are not picked up this extension. And the next logical question would be is why they are not picked up by this extension. The answer is most likely that these images are either partially corrupted or incompatible with WebP (for instance because of incompatible alpha-transparency or something else). You can convert these images manually to the proper format (JPEG 2000, JPEG XR, or still WebP).

I am going to close this issue now because it seems there is no issue with the extension itself, but more with how to interpret the results from the external tools.

**Comment by mark-netalico** [comment]
Thanks for the response! That makes sense. Would you ever consider adding an option to implement the webp images in a *not* backward compatible way?

**Comment by jissereitsma** [comment]
Yes, I would consider if somebody could point me in that direction. As I understand, the only way that WebP images will work in all browsers without custom workaround, is when all browsers support WebP.

**Comment by mark-netalico** [comment]
Since FF doesn't even support webp yet, maybe the option would be really more of a synthetic test to just kind of "prove" do speed tests that you're using webp.

**Comment by jissereitsma** [comment]
I'm not sure if this belongs to this extension anymore. The extension works (well?) and serves its purpose. However, because it is a custom-made solution, it is logical to assume that some reporting tools that do not support such a custom-made solution will report things in a wrong way.

The synthetic test you talk about does not apply to solutions like these. I get the feeling that you are pushing for a solution that is impossible to create. If you are a developer, please get technical on this, because I don't understand what you are aiming for. If you are not a developer, please accept the fact that WebP is not covered by all browsers, hence also not covered by all reporting tools. There is no debate needed on the fact that WebP is not supported by all tools.

But are you 100% confident about the question I raised earlier? Is the report actually about the images replaced by this extension, or is your site simply shipped with images that are not optimized yet for WebP because they are using wrong opacity or are broken? I would invest my time really in that first, because by scanning your HTML I can see dozens of images that need to be optimized. The reporting tools seem correct: Your images are lacking. And our extension is unable to convert those images automatically, because of reasons. You could also drop the discussion and simply make sure that those images are optimized. Perhaps then the reporting tools say that nothing else needs to optimized after all, and this issue was raised by a false assumption?

**Comment by mark-netalico** [comment]
Oohhh. Sorry. I just realized that some of the jpeg's aren't getting converted and that's probably more the reason why. Is there any way to force the conversion on non-template images? Like for that site, the slider has jpeg's but they're getting converted to webp.

**Comment by jissereitsma** [comment]
No, this is where this extension stops. Some extensions (non-template based) require custom work to have them convert to WebP. Most likely because they are JS-based and not HTML-based. Other images in the HTML itself can be converted by using `cwebp` from the command-line or any other convertor that you can find via Google. Once there is an image that has a corresponding WebP image in the same folder, the extension tries to pick up on it.
