### ISSUE TITLE
FrontEnd error 500

### ISSUE THREAD

**Issue by Danieleeffe1** [yireo/Yireo_Webp#10]
After compiling the files in Magento the system returns error in the Frontend

If the "scr" compiler method is disabled the plug-in function, if the "stat" compiler option is active the plug-in works.

magento 1.9.4.4
php 5.6

How do I solve?

**Comment by jissereitsma** [comment]
If there is a 500 Internal Server Error, it means that the actual PHP error is hidden. Could you supply the actual PHP error? Because otherwise, it is impossible to troubleshoot a thing like this.

**Comment by jissereitsma** [comment]
Please note that PHP 5.6 is not supported either: https://github.com/yireo/Yireo_Webp/blob/master/composer.json#L15 It is not supported by PHP, Magento and this extension. Because of this, I'm going to assume that this extension is only used, after you have upgraded to PHP 7 and theoretically this solves the issue. I'm going to close this issue because of this mismatch of requirements. Feel free to reopen once PHP has been upgraded. Please note that NOT upgrading PHP means that you are a thief to your own pocket - looking at security, support and performance.

**Comment by Danieleeffe1** [comment]
Good morning
thanks for the quick response.

I apologize for my english I'm using google translator.

I installed the extension manually via ftp as I use hosting with cPanel

I have brought php from 5.6 to 7.0

error 500 remains

I have tried from php 7.0 to 7.1

The error remains after compiling magento

Il giorno mer 10 giu 2020 alle ore 09:52 Jisse Reitsma <
notifications@github.com> ha scritto:

**Comment by jissereitsma** [comment]
Unfortunately, there is little I can do. The meaning of "500 Internal Server Error" is "Please look into the system logs for the real log, because this is the way the server is configured". Please contact your hosting provider for help on this matter.

**Comment by Danieleeffe1** [comment]
grazie

Il giorno mer 10 giu 2020 alle ore 12:09 Jisse Reitsma <
notifications@github.com> ha scritto:
