### ISSUE TITLE
Firefox images are not loading

### ISSUE THREAD

**Issue by WouterStulp** [yireo/Yireo_Webp#12]
I am having a problem that the images in Firefox on the product page are not loading, only when the whole page is reloaded. This problem does not excist in Chrome.

What browser did you test this with? 
**Firefox**
    What is your Magento version? What is your PHP version?
**Magento: 1.9.2.2 PHP 7.0.33**
    Which version of the Yireo WebP extension did you install?
**1.0.6**
        Don't say the latest but please provide the actual version number :)
    How did you install this module?
**Copy Files**
        Which composer command did you use, or did you copy files?
        What did you do to enable the module?
    Have you tested this after flushing all caches?
    Under System > Configuration > Web > WebP Images, what settings do you see?
        Value of Enabled
**Yes**
        Value of cwebp Method Enabled
**no**
        Value of Path to cwebp
**/usr/local/bin/cwebp**
        Value of GD Method Enabled
**Yes**
        Value of Disable with transparent images
**Yes**
        Value of Load WebP CSS
**No**
        Information on GD support
    What is the location of the cwebp binary on your system?
        Which version of cwebp is it?
        Did you try to manually convert troubling images using this CLI?
**I did not, all images are not working**
    Could you supply a URL to a live demo?
I have a video on Imgur: https://imgur.com/a/Eb6HmoW

**Comment by jissereitsma** [comment]
Thanks for addressing this. I assume you are using a Firefox version newer than 64? Could you confirm the version of Firefox anyway? The current WebP extension doesn't distinguish between browser versions but uses simple techniques to determine WebP support. If Firefox is not supporting this properly, there is little we can do. There is a newer technique though - simply replacing every `img` tag with a `picture` tag, so that it really is up to the browser to see which image is loaded. Unfortunately, this requires a complete rewrite, while Magento 1 has reached an EOL and we have already begun a year ago to fade out Magento 1 extensions. 

I watched the video and didn't see how you could conclude WebP images are or are not working. Please note that watching them in the Error Console does not work well, because then both the original images and the WebP images will be loaded.

**Comment by WouterStulp** [comment]
Hi,
Im using Firefox version 74.0.1

The video shows me loading the page, then where the image is supposed to be, its blank. Then i press F5 and the image loads.

So when we use a `picture` tag in an magento template you think i will work?

**Comment by jissereitsma** [comment]
No, that's not what I meant. The extension currently does not have support for `picture` tags. If you have a `picture` tag you are already pointing it to a JPG and a WebP and other formats, so the problem to optimize images is already solved. To make this extension solve that same problem, the extension would need to generate `picture` tags based on `img` tags. But as I mentioned, there is no roadmap for that anymore, because M1 is EOL and I'm personally moving away from M1 as well.

Still, it might be simply a browser issue.

**Comment by WouterStulp** [comment]
Thanks for the info!
