### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by iloa08** [yireo/Yireo_Webp#13]
Hi,
Got a problem with Infinite scroll (blank img) with this module : 
https://github.com/Strategery-Inc/Magento-InfiniteScroll
Image is 
src="https://xxx/skin/frontend/default/default/images/webp/placeholder.png"

Thanks.

**Comment by jissereitsma** [comment]
Thanks for addressing this. It seems both extensions are trying to update images via JavaScript which is not possible. Simply try one. Also, note that both extensions are deprecated because Magento 1 reached End-Of-Life half a year ago. My advice is not to invest too much in Magento 1, but save the time and money for migration. The fact that both extensions are clearly mentioning their deprecation on their homepages, should say enough here.
